#!/usr/bin/python
# -*- coding: utf-8 -*-
import sqlite3
con = sqlite3.connect('generateur.db') # Warning: This file is created in the current directory

## OBJETS
con.execute("CREATE TABLE objets (id INTEGER PRIMARY KEY, texte char(100) NOT NULL, status bool NOT NULL)")

# singulier masc
con.execute("INSERT INTO objets (texte,status) VALUES ('un éléphant',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('ton voisin',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('Dr Who',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un orang-outan',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('Victor Hugo',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un chef cuisto',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un personnage de Star Wars',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un virus dangereux',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('le doyen de l`humanité',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un sac à dos',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un personnage de Game of Thrones',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un bonhomme de neige',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('Paf le chien',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un nain',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un grand-père',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('le dernier des Apaches',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un(e) politicien(ne) que vous détestez',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un cow-boy ou une cow-girl',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un détective privé',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un poivrot',1)")
# singulier fem
con.execute("INSERT INTO objets (texte,status) VALUES ('la mère Michelle',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('une bucheronne canadienne',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('une ado geek',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('une fusée',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('une machine à remonter le temps',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('l`armée des zombies',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('une famille Playmobil',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('la Mort',1)")
# pluriel masc
con.execute("INSERT INTO objets (texte,status) VALUES ('des pirates',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('des champignons',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un régiment d`escargots',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('des irréductibles gaulois',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('une invasion d`extra-terrestres',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('une bande scouts',1)")
# pluriel fem
con.execute("INSERT INTO objets (texte,status) VALUES ('les pyramides d`Égypte',1)")
con.execute("INSERT INTO objets (texte,status) VALUES ('un bol de mignonnes petites cacahuètes',1)")


## SITUATIONS
con.execute("CREATE TABLE situations (id INTEGER PRIMARY KEY, texte char(100) NOT NULL, status bool NOT NULL)")

# neutre
con.execute("INSERT INTO situations (texte,status) VALUES ('vs un smartphone',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('un lundi matin',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au secours d`un-e prince-sse',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au Moyen-Âge, dans un donjon assiégé',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au musée du Louvre',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans une forêt magique',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans une montgolfière',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans un asile de fous',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('apprenant à voler',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('aux sports d`hiver',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('à l`aquagym',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au concert de Louane',1)")
con.execute("INSERT INTO situations (texte,status) VALUES (', frappé(e) d`une mort inattendue',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('devant un banquet pantagruélique',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('à la pompe à essence',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('en galère dans un pays étranger',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('sur une plage',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('sous l`orage',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('avec une grosse hache',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('victime d`un psychopate',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans un orchestre symphonique',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans un film Disney',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au marché, le dimanche matin',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans un désert (cactus autorisés)',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('sur une nouvelle planète',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au paradis',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au volant de la papamobile',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au Hellfest',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('en campagne électorale',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au camping des flots bleus',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('en atterrissage d`urgence',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans un siècle ou deux',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('aux Jeux Olympiques',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans une vente aux enchères',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('à ton anniversaire',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('à la piscine',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans un cabinet de voyante extra-lucide',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('au bal des pompiers du 14 juillet',1)")
# singulier
con.execute("INSERT INTO situations (texte,status) VALUES ('avec ses pokémons',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui fait du patin à glace',1)")
con.execute("INSERT INTO situations (texte,status) VALUES (', son ange gardien et son petit diabe intérieur',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui apprend à voler',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui fait une crise d`agoraphobie',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui sort d`une machine à remonter le temps',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui discute avec un réverbère',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui fait le ménage',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui a peur de son ombre / des miroirs',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('dans sa plus tendre enfance',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('complètement bourré(e)',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('en tutu',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui apprend à jouer d`un instrument de musique',1)")
# pluriel
con.execute("INSERT INTO situations (texte,status) VALUES ('qui font une manif',1)")
con.execute("INSERT INTO situations (texte,status) VALUES ('qui font la révolution',1)")

con.commit()
